title: 로체샤르 블로그
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://lhotse-shar.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
aux_links_new_tab: true

favicon_ico: "/assets/images/favicon.ico"

# plugins:
#   - jekyll-default-layout